---
title: "AdvancedGgplot2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R ggplot2

Travail avancé sur la libraire ggplot2. On commence par importer les bibliothèques nécessaires.

```{r load, warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
library(plotly)
```

## General appearance

On travaille sur les prix des Airbnb de la côte d'Azur

```{r 1st chart, warning=FALSE, message=FALSE}
# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/3_TwoNumOrdered.csv", header=T)
data$date <- as.Date(data$date)

#plot
data %>%
  ggplot( aes(x = date, y = value)) +
    geom_line(color = "#69b3a2") +
    annotate(geom = "point", x =as.Date("2017-12-17"),y = 20089, size = 10, shape = 21)+
    annotate(geom = "text", x = as.Date("2016-11-17"), y=20089, label ="Pic de valeur atteint par le bitcoin") + 
    geom_hline(yintercept = 5000)
    
```